### ISSUE TITLE
[Enhancement] Add Live Share support for DRM media players (Widevine, FairPlay, etc.)

### ISSUE THREAD

**Issue by corinagum** [microsoft/live-share-sdk#14]
The Teams desktop client does not currently support DRM. Our client currently runs in Electron, which has discontinued active support for the feature. We are investigating how to resolve this and will post updates here.

**Comment by ryanbliss** [comment]
_Update on this topic:_

Teams is a cross platform app that works on desktop, web, iOS, Android, and more; Widevine / DRM support varies by client. Last year, we announced that Teams is moving away from our current Electron-based desktop client in favor of Edge WebView2, starting with consumer users in Windows 11. While we haven't publicly announced a date for when that will roll out for Work and Education users, it is coming.

**T1: Electron Desktop (Mac + Windows)**

Our Electron client doesn't support Widevine, but it is technically possible. We've done a PoC using a [castLabs fork of Electron](https://github.com/castlabs/electron-releases/) for development builds, which is recommended by Electron. Using their 3PL partner status, castLabs has a CLI tool for this fork called EVS that supports self-serve app signing so that app builds can support production Widevine requirements.

Most of our meeting usage being in T1, so this is a major gap. With the transition to WebView2 incoming, major investments in T1 are scrutinized carefully. This work is _not_ funded for our next fiscal year, but do let us know if your scenario requires it.

**Web + T2: Edge WebView2** (Windows to start, Mac to follow)

One of the benefits we've found with our T2 client is that it does support Widevine out of the box. WebView2 uses a runtime bundled with the Edge browser, which already meets the Widevine specifications. In contrast, Electron bundles a separate Chromium runtime into each app, which means they need to be certified individually.

In the Chrome and Edge versions of Teams however, Widevine is supported today, but there is some work needed. To get the "encrypted-media" permission added to your tab app's iFrame, there is some work needed on your end. At a high level, you must first add the "media" permission to your app manifest and then programmatically request access to the permission. Here are a couple of documentation links that will help you get started:
- [Request device permissions](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=mobile%2Cteamsjs-v2)
- [Integrate media capabilities](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/media-capabilities?tabs=mobile) (up to the app manifest section)

**iOS + Android:**

DRM is supported on both iOS and Android, with FairPlay for iOS and Widevine for Android. Assuming your application supports the mobile browsers, it should work just fine in the WebView instances we host your app within.

We will consider this issue closed once DRM is supported in the Teams WebView2 desktop application for work and education customers. We will share more updates as we know more.

**Comment by ryanbliss** [comment]
Update: with the new Teams being GA'd as of last week, DRM is now technically supported. Currently, you must include the "media" permission in your app manifest for this to work. We are investigating improvements to this DevX, but it is at least possible now!

**Comment by ryanbliss** [comment]
Closing since this is supported in the new Teams, if you have questions please let us know.
