### ISSUE TITLE
Need to update documentation for Agile Poker sample app

### ISSUE THREAD

**Issue by sagar-malpure** [microsoft/live-share-sdk#234]
As per observations need to update below points for [Agile Poker sample app](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-teams-live-share?tutorial-step=2#feedback).

#1. The sub folder location is incorrect in step 4. It should be "live-share-sdk-main\samples\javascript\22.react-agile-poker"
![image](https://user-images.githubusercontent.com/85691087/207110772-d237f5dc-acf3-45b7-b290-fc0964cbf872.png)

#2. In step 8 space is required between port 3000 and --host. It should be like "ngrok http 3000 --host-header=localhost"

#3. To run above command it requires ngrok account. (can we mention this in doc) because we observed below error. 

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/85691087/207111973-dc4d1ebe-bfef-4076-b9c7-94192321da9a.png)

Thanks !

**Comment by corinagum** [comment]
Hi @sagar-malpure apologies for the late response!

✅  Since you filed your issue, it looks like the `cd ` into the directory has been fixed. I also don't see it in the other samples. Thanks for pointing that out. 
✅  2 has also been corrected in the samples

3 is a good point. I'll make a quick PR to add needing an ngrok account.

Appreciate the feedback!

**Comment by sagar-malpure** [comment]
Great ! Thank you.
