### ISSUE TITLE
[JS Bug]: JavaScript sample "02.react-video" fails in install in Teams via sideload method

### ISSUE THREAD

**Issue by canxerian** [microsoft/live-share-sdk#307]
### Please review [FAQ and Known issues](https://github.com/microsoft/live-share-sdk/issues/8) before filing a new item!

- [✅] I have reviewed the FAQ and known issues and did not find my topic

**Describe the bug**

User is unable to sideload 02.react-video sample project in to Teams and receives the error message: "There was a problem reaching this app"

![Screenshot 2023-01-10 100437](https://user-images.githubusercontent.com/1138440/211521777-8e6d19b8-4605-46ea-940a-23e91a38b304.png)

**To Reproduce**

## Run the app locally
1. `cd samples\javascript\02.react-video\manifest`
3. `npm install`
4. `npm start`
5. `ngrok http 3000 --host-header=localhost`

## Create Microsoft app and modify manifest.json
1. Go to https://dev.teams.microsoft.com/apps and create a new app
2. Replace `"id": "<<YOUR-MICROSOFT-APP-ID>>"` in `samples\javascript\02.react-video\manifest\manifest.json with the newly created app ID
3. Replace `"configurationUrl": "https://<<BASE_URI_DOMAIN>>/config?inTeams=true"` with ngrok URL from step 5 above
4. Compress contents of `samples\javascript\02.react-video\manifest` to zip file

## Sideload package
1. Follow instructions from sample Readme: https://github.com/microsoft/live-share-sdk/tree/main/samples/javascript/03.live-canvas-demo#test-it-out

**Expected behavior**

The app can be sideloaded in to Teams

**Desktop(s) (please complete the following information):**

- OS: [e.g. macOS]

> Add any other context about the problem here.
It appears this issue also affects 21.react-media-template, but not 01.dice-roller and 03.live-canvas-demo (I have not tested with others)

**Comment by corinagum** [comment]
Hey @canxerian thanks for filing the bug. Couple questions (starting with the frustrating basics) :

* Are you using the latest code from `main` branch?
* Did you run `npm run build` before `npm start`?
* Have you built the project (`npm install`) from the root of the project previously? (Because it's a lerna monorepo, there's a possibility they the root install and sample install butt heads)
* Are you able to run the same sample locally?
* Are you seeing any errors when you install, build, or start the server?

Meanwhile I'll try this out on a fresh clone and report back if I repro.

**Comment by corinagum** [comment]
@canxerian This looks like it's related to some code / documentation fixes I'm working on right now. 

1. The README says to run `ngrok http 3000`, but that's assuming the client is running on that port. The vite.config file needs to be updated to include
```js
server: {
    port: 3000
}
``` 
to ensure it runs on the right port. 

2. Missing documentation regarding ngrok:

The other samples have this info, but this one does not (my apologies)

When you're trying out a sideload, you need to run `npm run start:https` instead of `npm run start` due to the extra config settings for ngrok.

Therefore, when you run `npm run start:https`, it uses the `vite.https-config.js` file, which needs to be updated to:

```js
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [react()],
    resolve: {
        preserveSymlinks: true
    },
    server: {
        hmr: {
            // Needed to make ngrok work with Vite
            clientPort: 443,
        },
        port: 3000,
    },
});
```

**Comment by canxerian** [comment]
Hi @corinagum, thanks for your speedy reply!

I ran the sample again with your suggestions but still hit the issue described above. Here's the error from the Teams DevTools console:
![image](https://user-images.githubusercontent.com/1138440/212321158-2f3b8189-a509-4d95-94f3-11373cdc4a96.png)

**Comment by corinagum** [comment]
Hmmm I'm sorry it's still not working for you. I used the 02 manifest just now and I was able to get the sample working. 

1. Just to confirm: is this error after you have installed the app to the meeting, and then when adding it using the [+] button in the ubar during the meeting? 
1. Does your ngrok URL include `/config?inTeams=true`?
1. Are there any unusual network traces in the network tab in dev-tools?
1. If you use your ngrok link in the browser (removing `/config?inTeams=true`), can you run the sample?

**Comment by corinagum** [comment]
Closing as resolved 🙂
