### ISSUE TITLE
[Bug]:  "RoleVerifier: timed out" errors with 0.3.1

### ISSUE THREAD

**Issue by pradeepananth** [microsoft/live-share-sdk#40]
### Please review [FAQ and Known issues](https://github.com/microsoft/live-share-sdk/issues/8) before filing a new item!

- [x] I have reviewed the FAQ and known issues and did not find my topic

Eoin (eoobrian) to provide logs and repro steps - see below discussion. 

> As of 10/7/2022, engineering team does not have a repro for this bug.

**Comment by eoinobrien** [comment]
It's hard to create clear repro steps as it appears randomly but I'll do my best.

**Repro** 
1. Start a scheduled meeting as the organizer
2. Open an App that has a live share Event which is limited to Organizer and Presenter. (For me it was sent on scroll of the app)
3. In a second window, join the meeting with a different account which has a presenter role
5. Invoke the event (scroll the page). You can continue to this a bunch of times
6. See the document scroll on account 2's meeting
7. Invoke the event from the second account. (In my scenario the event actually constantly fires due to user 1, scrolling user 2, which fires an event, which scrolls user 1, etc. but I don't think that is related)
8. Wait at least 5 minutes
9. Scroll again, sometimes the below error appears in the console
  ```invalidRole {"category":"error","error":"RoleVerifier: timed out getting roles for a remote client ID","clientType":"interactive","containerId":"c2b5be95-<snipped>","docId":"<snipped>```

**Expected**
To be able to scroll for the length of the meeting

**Screenshots**
![image](https://user-images.githubusercontent.com/6508687/181338111-a2af85ea-0d3d-449c-acb8-8745f9931b93.png)
I've shared a fiddler trace with Pradeep directly as I don't want to leak anything internal unintentionally. 

OS: Windows
Browser: Edge
Version: 103.0.1264.62 (Official build) (64-bit)

Tested on Web using Public Preview versions of Teams

**Comment by pradeepananth** [comment]
Fixed as of 1.0.0-preview.3
