### ISSUE TITLE
live state notifications stop when updating to v1.0.0-preview.10

### ISSUE THREAD

**Issue by mscherotter** [microsoft/live-share-sdk#528]
### Please review [FAQ and Known issues](https://github.com/microsoft/live-share-sdk/issues/8) before filing a new item!

- [X] I have reviewed the FAQ and known issues and did not find my topic

**Please note: any submissions with insufficient reproducible information will be marked as 'Waiting for customer input' and may be closed is there is no response**

**Describe the bug**
I have updating my live state code to use the new livestate.initialize() method and the livestate.set() method and now my state changed event handler is not getting triggered in the test server or in Teams.

> Provide a clear and concise description of what the bug is.

**To Reproduce**

> Steps to reproduce the behavior:
1. Update packages to 
    "@microsoft/live-share": "^1.0.0-preview.10",
    "@microsoft/live-share-canvas": "^1.0.0-preview.10",
    "@microsoft/teams-js": "^2.10.1",
    "fluid-framework": "~1.2.3",
2. change livestate initialize function calls to have initial state object
3. change livestate changestate() to livestate.set() calls
4. change function signature for stateChanged event
5. run app in test server and Teams - notice that stateChanged events are not being triggered.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop(s) (please complete the following information):**

- OS: Windows 11k
- Browser: chrome & edge

**Smartphone (please complete the following information):**

**Additional context**

> Add any other context about the problem here.

**Comment by ryanbliss** [comment]
I think I might know what the issue here. Are you calling `liveState.set(undefined)`, and is that when the listener isn't being called? Or have you tried setting it to other values, such as a string or object? 

Knowing what values are being passed in as your initial state and set param would be super helpful, thanks!!

**Comment by mscherotter** [comment]
I am not calling liveState.set(undefined) .  I always call liveState set with a JSON object.

**Comment by mscherotter** [comment]
Do all members need to call livestate.initialize()?  What state parameters should I specify if I don't want visitors to update the live state?

**Comment by mscherotter** [comment]
I was just able to fix it by calling initialize() for the visitors as well as the host, even though I don't want to set the state for the visitors.

**Comment by ryanbliss** [comment]
Hey Michael, the initial state on .initialize() is not broadcasted out and will not trigger a changed event. It is just the default state, which you could make undefined in the initializerc and when the presenter connects you can then call `.set("whatever")` on their client. Even if someone joins late, the initial state will not override what was there beforehand. 

It's just a default value, since many use cases you don't want to have to have state start as undefined (eg countState.initialize(0)). The default state will be at that initial state until the remote state starts coming in, which will always override that default value.

**Comment by ryanbliss** [comment]
And yes, for all of our DDS's, all users need to call .initialize(), since that is what starts listening for socket events.
